#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but in the 9th time, it will display "Hi" instead of "Best School"
#

i=0
while ((i < 10)); do
	if ((i == 9)); then
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
