#!/usr/bin/env bash
# This script from 1 to 20 but after 4, 9 and 17, it will display a message

i=0
while ((i < 20)); do

	echo $i
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bas luck from Italy"
		;;
	esac

	((i++))
done
